### ISSUE TITLE
[F-R] Request to add an option to make shosetsu the default epub reader so that we can read downloaded epubs on shosetsu as well

### ISSUE THREAD

**Issue by rsmyst** [shosetsuorg/android-app#119] opened 2021-03-02 07:48 UTC
I wan't able to find one of the light novels i'm reading currently on any of the sites available as extensions. The LN is called adachi to shimamura. I download the novels from a github page where the translated LN is available. The thing is, i want to read it on my android device instead of my laptop. So i thought shosetsu might have a built in function for reading from local storage which sounds pretty basic to me. Tachiyomi has a function like this. 

Add a feature to allow reading epubs and LNs from local storage.

No alternatives yet other than using another app instead :(
I really like this app though. The UI is so close to tachiyomi and material design 2!

**Comment by Nan123721** [comment] 2021-05-27 04:23
I can agree here. This would be something simple to implement and seems like a necessity to me. Bumping!

**Comment by Doomsdayrs** [comment] 2021-06-16 04:54
Duplicate of #29

**Closed by Doomsdayrs** 2021-06-16 04:54 UTC
Labels: enhancement
