### ISSUE TITLE
Extension install bug [1656]

### ISSUE THREAD

**Issue by Palloxin** [shosetsuorg/android-app#172] opened 2021-12-13 18:35 UTC
**Describe the bug**
Installing a certain extension you will not be able to install more extension making the installation system stop working

**To Reproduce**
1. Try to insta the extension Rain of Snow Translation
2. try to install another extension
3.  '....'
4. Every installatuon will load forever endlessly

**Expected behavior**
the apl should install itself

**Screenshots**

**Device information:**
 - OS: android 8
 - App Version: 2.0 1656

**Additional context**
to fix it one must clear the data of the app

**Comment by khonkhortisan** [comment] 2021-12-14 23:47
This is a duplicate of https://github.com/shosetsuorg/android-app/issues/161 or https://github.com/shosetsuorg/android-app/issues/163 which were fixed with https://github.com/shosetsuorg/android-app/pull/164 which won't get to the users until there's a new release or people build it for themselves

**Comment by TechnoJo4** [comment] 2021-12-15 01:21
Duplicate of #161

**Closed by TechnoJo4** 2021-12-15 01:21 UTC
Labels: bug
