### ISSUE TITLE
[F-R] Option to disable next/prev chapter gesture

### ISSUE THREAD

**Issue by Xanvial** [shosetsuorg/android-app#116] opened 2021-02-17 16:12 UTC
**Is your feature request related to a problem? Please describe.**
From using this app a few days, I noticed that sometimes when scrolling the page, it jumps to next chapter prompt even though there's still many pages left.
After trying a few things, I just realized that there's a gesture option with swiping horizontal and the vertical up/down to jump between chapters. 

**Describe the solution you'd like**
Additional option to disable the gesture to move between chapters

**Describe alternatives you've considered**
Check the horizontal movement before triggering move chapters gesture, for example only if the horizontal movement is more than a third of screen width.
This should minimize accidental trigger

**Additional context**

**Comment by Doomsdayrs** [comment] 2021-02-17 16:51
Duplicate of #109

**Closed by Doomsdayrs** 2021-02-17 16:51 UTC
Labels: enhancement
